name: 'Docker Greeting Action'
description: 'Greets someone using a Docker container'
inputs:
  who-to-greet:  # Changed from 'name' to match what we'll pass to the entrypoint
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }} 