name: 'Greet User (JavaScript)'
description: 'Greets a user using JavaScript'
inputs:
  name:
    description: 'Name of the person to greet'
    required: true
    default: 'World'
runs:
  using: 'node20'
  main: 'index.js' 