name: Branch and Path Filters
on:
#   push:
#     branches:
#       - main
#       - 'feature/**'        # Matches feature/test, feature/new
#       - '!feature/private'  # Excludes feature/private
#     paths:
#       - '**.js'            # Any .js file
#       - '!tests/**'        # Exclude files in tests directory
#   pull_request:
#     branches: [ main, develop ]
#     paths-ignore:
#       - 'docs/**'
#       - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show triggered event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}" 