name: Composite Greeting Workflow
on:
  workflow_dispatch:

jobs:
  composite-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Composite greeting action
        uses: ./.github/actions/composite-actions
        with:
          name: "Composite User" 