name: Docker Greeting Workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  docker-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Docker greeting action
        uses: ./.github/actions/docker-actions
        with:
          name: "Docker User" 