name: Docker Greeting Workflow
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  docker-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Debug - List files before
        run: |
          pwd
          ls -la .github/actions/docker-actions/
          cat .github/actions/docker-actions/entrypoint.sh
      
      - name: Set file permissions
        run: chmod +x .github/actions/docker-actions/entrypoint.sh
      
      - name: Run Docker greeting action
        uses: ./.github/actions/docker-actions
        with:
          who-to-greet: "Docker User" 