name: JavaScript Greeting Workflow
on:
  workflow_dispatch:

jobs:
  js-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies
        working-directory: .github/actions/js-actions
        run: npm install
      
      - name: Run JavaScript greeting action
        uses: ./.github/actions/js-actions
        with:
          name: "JavaScript User" 