name: Tags and Releases
on:
#   push:
#     tags:
#       - 'v*.*.*'           # Matches v1.0.0, v2.1.3, etc.
#       - '!v*.*.*-alpha*'   # Excludes alpha releases
#   release:
#     types: [published, edited]
    workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Release
        run: |
          echo "Tag: ${{ github.ref }}"
        #   echo "Release type: ${{ github.event.action }}" 